# Generated by Django 6.0.7 on 2026-08-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Correo electrónico')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre')),
                ('origen', models.CharField(default='Formulario de contacto', max_length=100, verbose_name='Origen')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de suscripción')),
            ],
            options={
                'verbose_name': 'Suscriptor de Newsletter',
                'verbose_name_plural': 'Suscriptores de Newsletter',
                'ordering': ('-creado_en',),
            },
        ),
    ]
