# Generated by Django 6.0.7 on 2026-08-28 03:05

import django.db.models.deletion
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.ForeignKey(help_text='Selecciona el usuario del sistema al que pertenece este perfil.', on_delete=django.db.models.deletion.CASCADE, related_name='author_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del sistema'),
        ),
        migrations.CreateModel(
            name='BlogPostFuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('nombre', models.CharField(help_text="Ej: 'The New York Times', 'Banco Central', 'Reuters'", max_length=120, verbose_name='Nombre de la fuente / medio')),
                ('enlace', models.URLField(blank=True, verbose_name='Enlace a la fuente (opcional)')),
                ('foto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo o imagen de la fuente (opcional)')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuentes', to='blog.blogpostpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
