# Generated by Django 6.0.7 on 2026-08-28 04:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_author_user_blogpostfuente'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Si se deja en blanco, tomará la fecha y hora actual automáticamente.', verbose_name='Fecha de publicación'),
        ),
    ]
