# Generated by Django 6.0.7 on 2026-08-29 18:26

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpostpage_fecha_publicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostpage',
            name='categoria',
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='allowed_categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Deja vacío para permitir todas las categorías en este blog.', related_name='allowed_in_blogs', to='blog.blogcategory', verbose_name='Categorías permitidas'),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='categorias',
            field=modelcluster.fields.ParentalManyToManyField(help_text='Selecciona al menos una categoría para este artículo.', related_name='posts', to='blog.blogcategory', verbose_name='Categorías'),
        ),
    ]
