# Generated by Django 6.0.7 on 2026-08-31 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blogpostpage_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpostpage',
            old_name='categorias',
            new_name='categories',
        ),
    ]
