# Generated by Django 6.0.7 on 2026-08-31 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_categorias_blogpostpage_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='share_cta_text',
            field=models.CharField(blank=True, help_text="Ej: 'Compártelo'. Si se deja en blanco, usará el texto predeterminado ('Compártelo').", max_length=100, verbose_name='Texto de llamada a la acción para compartir'),
        ),
    ]
