# Generated by Django 6.0.7 on 2026-08-31 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpostpage_share_cta_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostpage',
            name='share_cta_text',
        ),
    ]
