# Generated by Django 6.0.7 on 2026-09-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogindexpage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_logo',
            field=models.BooleanField(default=False, help_text='Marcar si esta imagen es un logo institucional en lugar de una foto personal.', verbose_name='Es logotipo'),
        ),
    ]
