# Generated by Django 6.0.7 on 2026-08-27 21:18

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_homepage_body_homepage_cuerpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='cuerpo',
            field=wagtail.fields.StreamField([('inicio', 9)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Imagen de portada del bloque de inicio.', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Titular del bloque de inicio.', 'max_length': 25, 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Subtitular del bloque de inicio.', 'max_length': 50, 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Imagen del bloque de inicio.', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Texto del botón', 'max_length': 25, 'required': True}), 5: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Página interna'}), 6: ('wagtail.blocks.URLBlock', (), {'label': 'URL externa'}), 7: ('wagtail.blocks.StreamBlock', [[('pagina', 5), ('url_externa', 6)]], {}), 8: ('wagtail.blocks.StructBlock', [[('texto_boton', 4), ('enlace', 7)]], {'help_text': 'Botón del bloque de inicio.', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('portada', 0), ('titular', 1), ('subtitular', 2), ('imagen', 3), ('boton', 8)]], {})}),
        ),
    ]
