# Generated by Django 6.0.7 on 2026-08-27 23:42

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_homepage_cuerpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='cuerpo',
            field=wagtail.fields.StreamField([('inicio', 8)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Imagen de portada del bloque de inicio.', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Titular del bloque de inicio.', 'max_length': 150, 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Subtitular del bloque de inicio.', 'max_length': 250, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Texto del botón', 'max_length': 25, 'required': True}), 4: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Página interna'}), 5: ('wagtail.blocks.URLBlock', (), {'label': 'URL externa'}), 6: ('wagtail.blocks.StreamBlock', [[('pagina', 4), ('url_externa', 5)]], {}), 7: ('wagtail.blocks.StructBlock', [[('texto_boton', 3), ('enlace', 6)]], {'help_text': 'Botón del bloque de inicio.', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('portada', 0), ('titular', 1), ('subtitular', 2), ('boton', 7)]], {})}),
        ),
    ]
