# Generated by Django 6.0.7 on 2026-08-28 00:54

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_homepage_cuerpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='cuerpo',
            field=wagtail.fields.StreamField([('inicio', 8), ('nosotros', 17), ('servicios', 25)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Imagen de portada del bloque de inicio.', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Titular del bloque de inicio.', 'max_length': 150, 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Subtitular del bloque de inicio.', 'max_length': 250, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Texto', 'label': 'Texto del botón', 'max_length': 50, 'required': True}), 4: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Selecciona una página existente de tu sitio web.', 'label': 'Página interna'}), 5: ('wagtail.blocks.URLBlock', (), {'help_text': 'O escribe una URL completa (ej. https://ejemplo.com).', 'label': 'Enlace externo'}), 6: ('wagtail.blocks.StreamBlock', [[('pagina', 4), ('url_externa', 5)]], {}), 7: ('wagtail.blocks.StructBlock', [[('texto', 3), ('enlace', 6)]], {'help_text': 'Botón del bloque de inicio.', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('portada', 0), ('titular', 1), ('subtitular', 2), ('boton', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'default': 'Sobre Nosotros', 'label': 'Título de la sección', 'max_length': 100, 'required': True}), 10: ('wagtail.blocks.TextBlock', (), {'label': 'Subtítulo o descripción introductoria', 'required': False, 'rows': 2}), 11: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Foto de la empresa / equipo', 'required': False}), 12: ('wagtail.blocks.TextBlock', (), {'label': 'Misión', 'required': True, 'rows': 4}), 13: ('wagtail.blocks.TextBlock', (), {'label': 'Visión', 'required': True, 'rows': 4}), 14: ('wagtail.blocks.CharBlock', (), {'label': 'Nombre del valor', 'max_length': 60, 'required': True}), 15: ('wagtail.blocks.StructBlock', [[('titulo', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {'label': 'Valores corporativos', 'min_num': 1}), 17: ('wagtail.blocks.StructBlock', [[('titular', 9), ('subtitular', 10), ('logo', 11), ('mision', 12), ('vision', 13), ('valores', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'default': 'Nuestros servicios', 'label': 'Título de la sección', 'max_length': 100, 'required': True}), 19: ('wagtail.blocks.TextBlock', (), {'label': 'Subtítulo o descripción', 'required': False, 'rows': 2}), 20: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Proporción recomendada vertical o 4:5', 'label': 'Foto del servicio', 'required': True}), 21: ('wagtail.blocks.CharBlock', (), {'label': 'Título del servicio', 'max_length': 60, 'required': True}), 22: ('wagtail.blocks.TextBlock', (), {'label': 'Descripción breve', 'max_length': 200, 'required': True, 'rows': 3}), 23: ('wagtail.blocks.StructBlock', [[('imagen', 20), ('titulo', 21), ('descripcion', 22), ('pagina', 4)]], {}), 24: ('wagtail.blocks.ListBlock', (23,), {'label': 'Lista de servicios', 'max_num': 12, 'min_num': 4}), 25: ('wagtail.blocks.StructBlock', [[('titular', 18), ('subtitular', 19), ('servicios', 24)]], {})}),
        ),
    ]
