# Generated by Django 6.0.7 on 2026-08-28 03:47

import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.forms.models
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_homepage_cuerpo'),
        ('wagtailcore', '0098_apitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, validators=[wagtail.contrib.forms.models.validate_to_address], verbose_name='to address')),
                ('from_address', models.EmailField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('subtitular', models.CharField(blank=True, help_text="Ej: 'Conversemos sobre cómo potenciar la comunicación de tu empresa.'", max_length=255, verbose_name='Subtítulo')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Texto introductorio / Información de contacto')),
                ('mensaje_agradecimiento', wagtail.fields.RichTextField(blank=True, help_text='Mensaje que verá el usuario tras enviar el formulario.', verbose_name='Mensaje de éxito')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='cuerpo',
            field=wagtail.fields.StreamField([('hero', 8), ('about', 17), ('servicios', 25), ('clientes', 32), ('testimonios', 41), ('blog_feed', 48), ('contacto', 53)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Imagen de portada del bloque de inicio.', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Titular del bloque de inicio.', 'max_length': 150, 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Subtitular del bloque de inicio.', 'max_length': 250, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Texto', 'label': 'Texto del botón', 'max_length': 50, 'required': True}), 4: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Selecciona una página existente de tu sitio web.', 'label': 'Página interna'}), 5: ('wagtail.blocks.URLBlock', (), {'help_text': 'O escribe una URL completa (ej. https://ejemplo.com).', 'label': 'Enlace externo'}), 6: ('wagtail.blocks.StreamBlock', [[('pagina', 4), ('url_externa', 5)]], {}), 7: ('wagtail.blocks.StructBlock', [[('texto', 3), ('enlace', 6)]], {'help_text': 'Botón del bloque de inicio.', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('portada', 0), ('titular', 1), ('subtitular', 2), ('boton', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'default': 'Sobre Nosotros', 'label': 'Título de la sección', 'max_length': 100, 'required': True}), 10: ('wagtail.blocks.TextBlock', (), {'label': 'Subtítulo o descripción introductoria', 'required': False, 'rows': 2}), 11: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Foto de la empresa / equipo', 'required': False}), 12: ('wagtail.blocks.TextBlock', (), {'label': 'Misión', 'required': True, 'rows': 4}), 13: ('wagtail.blocks.TextBlock', (), {'label': 'Visión', 'required': True, 'rows': 4}), 14: ('wagtail.blocks.CharBlock', (), {'label': 'Nombre del valor', 'max_length': 60, 'required': True}), 15: ('wagtail.blocks.StructBlock', [[('titulo', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {'label': 'Valores corporativos', 'min_num': 1}), 17: ('wagtail.blocks.StructBlock', [[('titular', 9), ('subtitular', 10), ('logo', 11), ('mision', 12), ('vision', 13), ('valores', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'default': 'Nuestros servicios', 'label': 'Título de la sección', 'max_length': 100, 'required': True}), 19: ('wagtail.blocks.TextBlock', (), {'label': 'Subtítulo o descripción', 'required': False, 'rows': 2}), 20: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Proporción recomendada vertical o 4:5', 'label': 'Foto del servicio', 'required': True}), 21: ('wagtail.blocks.CharBlock', (), {'label': 'Título del servicio', 'max_length': 60, 'required': True}), 22: ('wagtail.blocks.TextBlock', (), {'label': 'Descripción breve', 'max_length': 200, 'required': True, 'rows': 3}), 23: ('wagtail.blocks.StructBlock', [[('imagen', 20), ('titulo', 21), ('descripcion', 22), ('pagina', 4)]], {}), 24: ('wagtail.blocks.ListBlock', (23,), {'label': 'Lista de servicios', 'max_num': 12, 'min_num': 4}), 25: ('wagtail.blocks.StructBlock', [[('titular', 18), ('subtitular', 19), ('servicios', 24)]], {}), 26: ('wagtail.blocks.CharBlock', (), {'default': 'Nuestros clientes', 'label': 'Título de la sección', 'max_length': 100, 'required': True}), 27: ('wagtail.blocks.TextBlock', (), {'default': 'Empresas que confían en nosotros', 'label': 'Subtítulo (opcional)', 'required': False, 'rows': 2}), 28: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Logo rectangular con fondo transparente (PNG, SVG o WebP).', 'label': 'Logo de la empresa', 'required': True}), 29: ('wagtail.blocks.URLBlock', (), {'help_text': 'Ejemplo: https://cliente.com', 'label': 'Sitio web del cliente', 'required': True}), 30: ('wagtail.blocks.StructBlock', [[('logo', 28), ('enlace_externo', 29)]], {}), 31: ('wagtail.blocks.ListBlock', (30,), {'label': 'Lista de clientes', 'max_num': 20, 'min_num': 1}), 32: ('wagtail.blocks.StructBlock', [[('titular', 26), ('subtitular', 27), ('clientes', 31)]], {}), 33: ('wagtail.blocks.CharBlock', (), {'default': 'Testimonios', 'label': 'Título de la sección', 'max_length': 100, 'required': True}), 34: ('wagtail.blocks.TextBlock', (), {'label': 'Subtítulo (opcional)', 'required': False, 'rows': 2}), 35: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Retrato de la persona (proporción cuadrada recomendada).', 'label': 'Foto de perfil', 'required': True}), 36: ('wagtail.blocks.TextBlock', (), {'help_text': 'Las palabras o reseña compartida por la persona.', 'label': 'Testimonio / Palabras', 'required': True, 'rows': 4}), 37: ('wagtail.blocks.CharBlock', (), {'label': 'Nombre completo', 'max_length': 80, 'required': True}), 38: ('wagtail.blocks.CharBlock', (), {'help_text': 'Ej: Directora Ejecutiva, Fundación Popular', 'label': 'Cargo / Profesión / Rol', 'max_length': 100, 'required': True}), 39: ('wagtail.blocks.StructBlock', [[('foto_perfil', 35), ('testimonio', 36), ('nombre', 37), ('cargo', 38)]], {}), 40: ('wagtail.blocks.ListBlock', (39,), {'label': 'Lista de testimonios', 'max_num': 6, 'min_num': 3}), 41: ('wagtail.blocks.StructBlock', [[('titular', 33), ('subtitular', 34), ('testimonios', 40)]], {}), 42: ('wagtail.blocks.CharBlock', (), {'default': 'Blog', 'help_text': "Ej: 'Blog Corporativo' o 'Columna de Opinión'", 'label': 'Etiqueta superior (Badge)', 'max_length': 40, 'required': False}), 43: ('wagtail.blocks.CharBlock', (), {'label': 'Título de la sección', 'max_length': 100, 'required': True}), 44: ('wagtail.blocks.TextBlock', (), {'label': 'Subtítulo o lema', 'required': False, 'rows': 2}), 45: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Elige la página índice del blog que quieres mostrar.', 'label': 'Seleccionar Blog', 'page_type': ['blog.BlogIndexPage'], 'required': True}), 46: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Úsalo para columnas personales como la de Néstor.', 'label': 'Foto de autor (opcional)', 'required': False}), 47: ('wagtail.blocks.IntegerBlock', (), {'default': 3, 'label': 'Cantidad de artículos', 'max_value': 6, 'min_value': 1}), 48: ('wagtail.blocks.StructBlock', [[('etiqueta', 42), ('titular', 43), ('subtitular', 44), ('pagina_blog', 45), ('foto_autor', 46), ('limite', 47)]], {}), 49: ('wagtail.blocks.CharBlock', (), {'default': 'Contacto', 'max_length': 40, 'required': False}), 50: ('wagtail.blocks.CharBlock', (), {'default': 'Hablemos de tu próximo proyecto', 'max_length': 120}), 51: ('wagtail.blocks.TextBlock', (), {'required': False}), 52: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Página de Contacto Destino', 'page_type': ['home.ContactPage']}), 53: ('wagtail.blocks.StructBlock', [[('etiqueta', 49), ('titular', 50), ('subtitular', 51), ('pagina_contacto', 52)]], {})}),
        ),
        migrations.CreateModel(
            name='ContactFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='home.contactpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
