# Generated by Django 6.0.7 on 2026-08-31 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_configuracionsitio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsitio',
            name='sufijo_titulo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Eslogan'),
        ),
    ]
