# Generated by Django 6.0.7 on 2026-08-31 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_configuracionsitio_blog_share_cta_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsitio',
            name='blog_share_cta_text',
            field=models.CharField(blank=True, default='Compártelo', help_text='Aparecerá en los botones de compartir de todos los artículos del blog.', max_length=100, verbose_name='Texto de llamada a la acción para compartir posts'),
        ),
    ]
