# Generated by Django 6.0.7 on 2026-09-01 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_homepage_cuerpo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='from_address',
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='subject',
            field=models.CharField(blank=True, default='Nuevo mensaje de contacto desde el sitio web', max_length=255, verbose_name='Asunto del correo'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='to_address',
            field=models.EmailField(blank=True, help_text='A dónde llegarán las notificaciones de contacto.', max_length=254, verbose_name='Correo de destino'),
        ),
        migrations.DeleteModel(
            name='ContactFormField',
        ),
    ]
