# Generated by Django 6.0.7 on 2026-09-01 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_homepage_cuerpo'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='imagen_compartir',
            field=models.ForeignKey(blank=True, help_text='Imagen por defecto para redes sociales (Ideal: 1200x630px)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
